<!--Criar o banco de dados
CREATE DATABASE CursoCrud;
USE CursoCrud;

<!-- Criar a tabela UF
CREATE TABLE UF (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    SIGLA VARCHAR(2),
    REGIAO VARCHAR(50)
);

-- Criar a tabela Municipio
CREATE TABLE Municipio (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    POPULACAO INT,
    UF_CODIGO INT,
    FOREIGN KEY (UF_CODIGO) REFERENCES UF(CODIGO)
);

-- Criar a tabela Aluno
CREATE TABLE Aluno (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    DATA_NCTO DATE,
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    MUNICIPIO_CODIGO INT,
    FOREIGN KEY (MUNICIPIO_CODIGO) REFERENCES Municipio(CODIGO)
);

-- Criar a tabela Disciplina
CREATE TABLE Disciplina (
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    NR_AULAS INT,
    MENSALIDADE DECIMAL(10, 2)
);

-- Criar a tabela Cursa (tabela associativa entre Aluno e Disciplina)
CREATE TABLE Cursa (
    ALUNO_CODIGO INT,
    DISCIPLINA_CODIGO INT,
    TURMA VARCHAR(50),
    ANO INT,
    NOTA1 DECIMAL(4, 2),
    NOTA2 DECIMAL(4, 2),
    FALTAS INT,
    PRIMARY KEY (ALUNO_CODIGO, DISCIPLINA_CODIGO),
    FOREIGN KEY (ALUNO_CODIGO) REFERENCES Aluno(CODIGO),
    FOREIGN KEY (DISCIPLINA_CODIGO) REFERENCES Disciplina(CODIGO)
);--> 